export const hackathonInfo = [
  {
    hackId: 1,
    hackName: "해커퉁1",
    startDate: "2024-12-1",
    endDate: "2024-12-31",
    link: "",
    memNumber: 4,
    maxMemNumber: 4,
    description: "오늘의 날씨를 알려주자!!!! ",
    video: "https://tv.naver.com/v/66037262",
    pictures: "",
    coverImage: "",
    logo: "",
    ownerId: "happytree12",
    ownerEmail: "tylove@naver.com",
    participant: ["admin1", "happytree12", "backendDevel1!"],
    part: "프론트엔드",
  },
  {
    hackId: 2,
    hackName: "해커톤2",
    startDate: "2024-11-1",
    endDate: "2024-12-31",
    link: "",
    memNumber: 20,
    maxMemNumber: 20,
    description: "설명입니다",
    video: "",
    pictures: "",
    coverImage: "",
    logo: "",
    ownerId: "backendDevel1!",
    ownerEmail: "sylove@naver.com",
    participant: ["happytree12"],
    part: "백엔드",
  },
];