export const projectInfo = [
  {
    projectId: 1,
    ownerId: "admin1",
    ownerName: "김예은",
    ownerNickname: "옝",
    ownerEmail: "nabinabi1110@naver.com",
    projectTemplate: 1,
    projectTitle: "마라탕후루",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.11.11",
    endDate: "2024.11.18",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: false,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 78,
    likes: ["happytree12"],
    contacts: [],
    comments: [],
  },
  {
    projectId: 2,
    ownerId: "admin1",
    ownerName: "김예은",
    ownerNickname: "옝",
    ownerEmail: "nabinabi1110@naver.com",
    projectTemplate: 1,
    projectTitle: "마루",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.11.12",
    endDate: "2024.11.22",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 59,
    likes: [],
    contacts: ["admin4"],
    comments: [10, 11],
  },
  {
    projectId: 3,
    ownerId: "happytree12",
    ownerName: "김태연",
    ownerNickname: "탱구리",
    ownerEmail: "tylove@naver.com",
    projectTemplate: 3,
    projectTitle: "탱의 포폴1",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.11.01",
    endDate: "2024.11.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "JavaScript",
    category: "프론트엔드",
    hits: 17,
    likes: [],
    contacts: ["admin4"],
    comments: [],
  },
  {
    projectId: 4,
    ownerId: "happytree12",
    ownerName: "김태연",
    ownerNickname: "탱구리",
    ownerEmail: "tylove@naver.com",
    projectTemplate: 2,
    projectTitle: "탱의 포폴2",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.10.01",
    endDate: "2024.10.10",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "JavaScript",
    category: "프론트엔드",
    hits: 8,
    likes: [],
    contacts: [],
    comments: [],
  },
  {
    projectId: 5,
    ownerId: "backendDevel1!",
    ownerName: "조수연",
    ownerNickname: "수여니",
    ownerEmail: "sylove@naver.com",
    projectTemplate: 2,
    projectTitle: "수여니의 포폴1",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.09.01",
    endDate: "2024.10.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Python",
    category: "백엔드",
    hits: 21,
    likes: ["suyeonnie2"],
    contacts: ["admin4"],
    comments: [10, 11, 12, 13, 14],
  },
  {
    projectId: 6,
    ownerId: "backendDevel1!",
    ownerName: "조수연",
    ownerNickname: "수여니",
    ownerEmail: "sylove@naver.com",
    projectTemplate: 1,
    projectTitle: "수여니의 포폴2",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.07.01",
    endDate: "2024.08.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 63,
    likes: [],
    contacts: ["admin4"],
    comments: [],
  },
  {
    projectId: 7,
    ownerId: "admin4",
    ownerName: "최현혜",
    ownerNickname: "현혜씽",
    ownerEmail: "hhlove@naver.com",
    projectTemplate: 3,
    projectTitle: "현혜씽의 포폴1",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.08.01",
    endDate: "2024.08.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 89,
    likes: [],
    contacts: ["admin1"],
    comments: [],
  },
  {
    projectId: 8,
    ownerId: "admin4",
    ownerName: "최현혜",
    ownerNickname: "현혜씽",
    ownerEmail: "hhlove@naver.com",
    projectTemplate: 2,
    projectTitle: "현혜씽의 포폴2",
    description: "현재 제가 만든 모든 프로그램을 정리하였습니다.",
    startDate: "2024.11.01",
    endDate: "2024.11.30",
    solving: "이러이러한 곳에 사용할 수 있습니다.",
    challenge: "이러이러한 문제를 해결했습니다.",
    share: true,
    usedLanguage: "Java",
    category: "백엔드",
    hits: 33,
    likes: [
      7
    ],
    contacts: [
      "admin1",
      "admin4"
    ],
    comments: []
  },
];